[package]
name = "apachelog"
version = "0.1.0"
authors = ["Martin Keegan <martin@no.ucant.org>"]
edition = "2018"

[dependencies]
clap = "*"
flate2 = { version = "1.0", features = ["zlib"], default-features = false }

